spring:
  config:
    activate:
      on-profile: common
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  sql:
    init:
      encoding: UTF-8
      continue-on-error: true
      mode: always

server:
  port: 80

---

spring:
  config:
    activate:
      on-profile: localdb
    import: localkey.yaml
  datasource:
    url: jdbc:mariadb://localhost:3306/lof
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

slack:
  token: ${localkey.slack-api.token}
fandascore:
  key: ${localkey.fandascore-api.key}

---

spring:
  config:
    activate:
      on-profile: serverdb
  datasource:
    url: ${lof.mariadb.url}/lof
    username: root
    password: ${lof.mariadb.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
slack:
  token: ${lof.slack.token}
fandascore:
  key: ${lof.pandascore.token}