spring:
  config:
    activate:
      on-profile: common
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  sql:
    init:
      encoding: UTF-8
      continue-on-error: true
      mode: always

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: localdb
    import: localkey.yaml
  datasource:
    url: jdbc:mariadb://localhost:3306/lof
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

token:
  slack: ${localkey.slack-api.token}
  pandascore: ${localkey.pandascore-api.key}

---

spring:
  config:
    activate:
      on-profile: serverdb
  datasource:
    url: ${lof.mariadb.url}/lofDev
    username: root
    password: ${lof.mariadb.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
token:
    slack: ${lof.slack.token}
    pandascore: ${lof.pandascore.key}